name: validate
on:
  pull_request:
  push:
  schedule:
    - cron: '11 21 * * *'
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: hashicorp/setup-terraform@v1
      - run: terraform fmt -check
      - run: terraform init
      - run: terraform validate
        env:
          AWS_DEFAULT_REGION: us-east-1
