name: validate
on:
  pull_request:
  push:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform fmt -check
      - run: terraform init
      - run: terraform validate
        env:
          AWS_DEFAULT_REGION: us-east-1
